CREATE TABLE events (
    event_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creation_time  TIMESTAMPTZ NOT NULL DEFAULT LOCALTIMESTAMP(0),
    event_title    TEXT NOT NULL,
    reminder_time  TIMESTAMPTZ NOT NULL,
    event_type     INT NOT NULL,
    message        TEXT
);